name: vupyapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shared_preferences: ^0.4.3
  page_transition: '^1.1.0'
  http: '>=0.11.3+12'
  bubble_bottom_bar: ^1.2.0
  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.3
  email_validator: '^1.0.0'
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.9
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - assets/vupylogo.png

  fonts:
      - family: vupyicons
        fonts:
            - asset: fonts/vupyFont.ttf
              weight: 400

      - family: Mont
        fonts:
            - asset: fonts/Montserrat-Regular.ttf

      
      # - family: Emojis
      #   fonts:
      #       - asset: fonts/vupyEmoji.ttf
